on:
  push:
    branches:
      - test_server
name: Auto-Prod Deploy
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.APP_USER }}
          server: ${{ secrets.APP_SERVER }}
          port: ${{ secrets.APP_PORT }}
          local_path: './*'
          remote_path: '/'
          sftp_only: true
          password: ${{ secrets.APP_PASSWORD }}
